swagger: '2.0'
info:
  description: 'This is a sample Hotels Server.  You can find out more about OpenAPI spec at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).'
  version: 1.0.0
  title: OpenAPI Specification for Hotels
  contact:
    name: Apigee
    url: https://pages.apigee.com/request-support-general.html
    email: support@apigee.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: api.usergrid.com
basePath: /demo24/sandbox
tags:
  - name: hotel
    description: Everything about Hotels
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
schemes:
  - https
paths:
  /hotels/{hotel-uuid}:
    get:
      summary: Get hotel by uuid
      description: This method will return a hotel by uuid from BaaS datastore
      parameters:
        - name: hotel-uuid
          in: path
          description: uuid of the hotel
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Response'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '404':
          $ref: '#/responses/404'            
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hotels:
    post:
      summary: Create new hotel
      description: This method will create a new hotel
      parameters:
        - name: hotel
          in: body
          description: Create a new hotel
          required: true
          schema:
            $ref: '#/definitions/HotelCreateRequest'
      responses:
        "201":
          description: successfully created a hotel
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      summary: Find all hotels
      description: This method will return a list of hotels from BaaS datastore
      parameters:
        - name: zipcode
          in: query
          description: find hotels near zipcode
          required: false
          type: string
        - name: radius
          in: query
          description: find hotels within radius
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/findHotelsResponse'
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  findHotelsResponse:
    properties:
      hotels:
        $ref: '#/definitions/Hotels'
    example:
      hotels: 
        queryparams: 
          zipcode: "null"
          radius: "null"
        resultsMetadata: 
          count: 10
          nextCursor: "LTU2ODc0MzQzOm1kMkstbzAtRWVXZ3RZSFFWVFhybkE"
        entities: 
          - 
            uuid: "99ba729a-8d3e-11e5-a524-3de0f1fd809e"
            type: "hotel"
            name: "Motif Seattle"
            created: 1447773571129
            modified: 1447781984272
            address1: "1415 5th Ave"
            airportCode: "SEA"
            amenityMask: 7798786
            city: "Seattle"
            confidenceRating: 52
            countryCode: "US"
            deepLink: "http://www.travelnow.com/templates/55505/hotels/125727/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null"
            highRate: 289
            hotelId: 125727
            hotelInDestination: true
            hotelRating: 4
            location: 
              latitude: 47.60985
              longitude: -122.33475
            locationDescription: "Near museums and stadiums"
            lowRate: 259
            metadata: 
              path: "/hotels/99ba729a-8d3e-11e5-a524-3de0f1fd809e"
            postalCode: 98101
            propertyCategory: 1
            proximityDistance: 11.168453
            proximityUnit: "MI"
            rateCurrencyCode: "USD"
            shortDescription: "&lt;p&gt;&lt;b&gt;Property Location&lt;/b&gt; &lt;br /&gt;With a stay at Motif Seattle, you&apos;ll be centrally located in Seattle, steps from 5th Avenue Theater and minutes from Pike Place Market. This 4-star hotel is within"
            stateProvinceCode: "WA"
            thumbNailUrl: "/hotels/1000000/60000/51000/50947/50947_264_t.jpg"
            tripAdvisorRating: 3.5
            tripAdvisorRatingUrl: "http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/3.5-12345-4.gif"
          - 
            uuid: "99be432a-8d3e-11e5-bbec-5360d463a875"
            type: "hotel"
            name: "The Westin Seattle"
            created: 1447773571154
            modified: 1447786020476
            address1: "1900 5th Ave"
            airportCode: "SEA"
            amenityMask: 7806977
            city: "Seattle"
            confidenceRating: 5
            countryCode: "US"
            deepLink: "http://www.travelnow.com/templates/55505/hotels/164122/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null"
            highRate: 259
            hotelId: 164122
            hotelInDestination: true
            hotelRating: 4
            location: 
              latitude: 47.61309
              longitude: -122.33788
            locationDescription: "Near Museums and Hotels"
            lowRate: 209
            metadata: 
              path: "/hotels/99be432a-8d3e-11e5-bbec-5360d463a875"
            postalCode: 98101
            propertyCategory: 1
            proximityDistance: 11.335604
            proximityUnit: "MI"
            rateCurrencyCode: "USD"
            shortDescription: "&lt;p&gt;&lt;b&gt;Property Location&lt;/b&gt; &lt;br /&gt;With a stay at The Westin Seattle, you&apos;ll be centrally located in Seattle, steps from Westlake Center and minutes from Pacific Place. This 4-star hotel is close to"
            stateProvinceCode: "WA"
            thumbNailUrl: "/hotels/1000000/20000/16700/16673/16673_260_t.jpg"
            tripAdvisorRating: 4
            tripAdvisorRatingUrl: "http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-12345-4.gif"
  Response:
    properties:
      action:
        type: string
      application:
        type: string
      path:
        type: string
      uri:
        type: string
      entities:
        type: array
        items:
          $ref: '#/definitions/Entity'
      timestamp:
        type: integer
        format: int64
      duration:
        type: integer
      organization:
        type: string
      applicationName:
        type: string
    example:
      action: "get"
      application: "621b1920-8d3e-11e5-9294-d7dd4527da2b"
      params: {}
      path: "/hotels"
      uri: "https://api.usergrid.com/demo2/sandbox/hotels"
      entities: 
        uuid: "99ba729a-8d3e-11e5-a524-3de0f1fd809e"
        type: "hotel"
        name: "Motif Seattle"
        created: 1447773571129
        modified: 1447781984272
        address1: "1415 5th Ave"
        airportCode: "SEA"
        amenityMask: 7798786
        city: "Seattle"
        confidenceRating: 52
        countryCode: "US"
        deepLink: "http://www.travelnow.com/templates/55505/hotels/125727/overview?lang=en&amp;currency=USD&amp;standardCheckin=null/null/null&amp;standardCheckout=null/null/null"
        highRate: 289
        hotelId: 125727
        hotelInDestination: true
        hotelRating: 4
        location: 
          latitude: 47.60985
          longitude: -122.33475
        locationDescription: "Near museums and stadiums"
        lowRate: 259
        metadata: 
          path: "/hotels/99ba729a-8d3e-11e5-a524-3de0f1fd809e"
        postalCode: 98101
        propertyCategory: 1
        proximityDistance: 11.168453
        proximityUnit: "MI"
        rateCurrencyCode: "USD"
        shortDescription: "&lt;p&gt;&lt;b&gt;Property Location&lt;/b&gt; &lt;br /&gt;With a stay at Motif Seattle, you&apos;ll be centrally located in Seattle, steps from 5th Avenue Theater and minutes from Pike Place Market. This 4-star hotel is within"
        stateProvinceCode: "WA"
        thumbNailUrl: "/hotels/1000000/60000/51000/50947/50947_264_t.jpg"
        tripAdvisorRating: 3.5
        tripAdvisorRatingUrl: "http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/3.5-12345-4.gif"
      timestamp: 1453832336157
      duration: 21
      organization: "demo2"
      applicationName: "sandbox"
  Hotels:
    properties:
      queryparams:
        $ref: '#/definitions/QueryParams'
      resultsMetadata:
        $ref: '#/definitions/ResultsMetadata'
      entities:
        type: array
        items:
          $ref: '#/definitions/Entity'
  QueryParams:
    properties:
      zipcode:
        type: string
      radius:
        type: string
  ResultsMetadata:
    properties:
      count:
        type: integer
      nextCursor:
        type: string
  Entity:
    properties:
      uuid:
        type: string
      type:
        type: string
      name:
        type: string
      created:
        type: integer
        format: int64
      modified:
        type: integer
        format: int64
      address1:
        type: string
      airportCode:
        type: string
      amenityMask:
        type: integer
      city:
        type: string
      confidenceRating:
        type: integer
      countryCode:
        type: string
      deepLink:
        type: string
      highRate:
        type: integer
      hotelId:
        type: integer
      hotelInDestination:
        type: boolean
      hotelRating:
        type: integer
      location:
        type: object
        properties:
          latitude:
            type: number
            format: double
          longitude:
            type: number
            format: double
      locationDescription:
        type: string
      lowRate:
        type: integer
      postalCode:
        type: integer
      propertyCategory:
        type: integer
      proximityDistance:
        type: number
        format: double
      proximityUnit:
        type: string
      rateCurrencyCode:
        type: string
      shortDescription:
        type: string
      stateProvinceCode:
        type: string
      thumbNailUrl:
        type: string
      tripAdvisorRating:
        type: number
        format: float
      tripAdvisorRatingUrl:
        type: string
  HotelCreateRequest:
    properties:
      type:
        type: string
      name:
        type: string
      created:
        type: integer
        format: int64
      modified:
        type: integer
        format: int64
      address1:
        type: string
      airportCode:
        type: string
      amenityMask:
        type: integer
      city:
        type: string
      confidenceRating:
        type: integer
      countryCode:
        type: string
      deepLink:
        type: string
      highRate:
        type: integer
      hotelId:
        type: integer
      hotelInDestination:
        type: boolean
      hotelRating:
        type: integer
      location:
        type: object
        properties:
          latitude:
            type: number
            format: double
          longitude:
            type: number
            format: double
      locationDescription:
        type: string
      lowRate:
        type: integer
      postalCode:
        type: integer
      propertyCategory:
        type: integer
      proximityDistance:
        type: number
        format: double
      proximityUnit:
        type: string
      rateCurrencyCode:
        type: string
      shortDescription:
        type: string
      stateProvinceCode:
        type: string
      thumbNailUrl:
        type: string
      tripAdvisorRating:
        type: number
        format: float
      tripAdvisorRatingUrl:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
responses:
  '400':
    description: Bad Request. Client request in error
    schema: {}
  '401':
    description: Unauthorized. Client authentication token missing from request
    schema: {}
  '403':
    description: Forbidden. Client authentication token does not permit this method on this resource
    schema: {}
  '404':
    description: Not Found. Resource not found
    schema: {}
